name: Common Setup for Stride Documentation

# This is not used currently. The job runs in a separate instants so can't be used
on:
  workflow_call:
    outputs:
      stride_docs_path:
        description: "The checkout path of the Stride Docs repository"
        value: ${{ jobs.setup.outputs.stride_docs_path }}
      stride_path:
        description: "The checkout path of the Stride repository"
        value: ${{ jobs.setup.outputs.stride_path }}

jobs:
  setup:
    runs-on: windows-2022

    outputs:
      stride-docs-path: 'stride-docs'
      stride-path: 'stride'

    steps:
    # Setup .NET SDK
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    # Checkout the Stride Docs repository from the branch that triggered the workflow
    - name: Checkout Stride Docs
      uses: actions/checkout@v4
      with:
        path: stride-docs
        lfs: true

    # Checkout the Stride repository from the default branch
    - name: Checkout Stride (note the LFS)
      uses: actions/checkout@v4
      with:
        repository: stride3d/stride
        token: ${{ secrets.GITHUB_TOKEN }}
        path: stride
        lfs: true

    - name: Install DocFX
      # This installs the latest version of DocFX and may introduce breaking changes
      # run: dotnet tool update -g docfx
      # This installs a specific, tested version of DocFX.
      run: dotnet tool update -g docfx --version 2.76.0
