name: Build Stride Docs for GitHub Staging

env:
  COMMON_SETTINGS_PATH: en/docfx.json
  VERSION: "2.0.0.${{ github.run_number }}"
  DOCS_PATH: stride-docs

on:
  workflow_dispatch:
    inputs:
      skipPdfBuilding:
        description: Skip PDF building
        required: true
        default: true
        type: boolean
      skipApiBuilding:
        description: Skip API building
        required: true
        default: true
        type: boolean

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    name: Build documentation
    runs-on: windows-latest

    steps:
    - name: Checkout Stride Docs
      uses: actions/checkout@v6
      with:
        path: ${{ env.DOCS_PATH }}
        lfs: true

    - name: Run Global Setup
      id: setup
      uses: ./stride-docs/.github/actions/setup-stride
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        skip-pdf-building: ${{ inputs.skipPdfBuilding }}
        skip-api-building: ${{ inputs.skipApiBuilding }}

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: ${{ env.DOCS_PATH }}/_site

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v5