# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build Stride Docs for GitHub Staging

env:
  COMMON_SETTINGS_PATH: en/docfx.json
  VERSION: "2.0.0.${{ github.run_number }}"
  DOCS_PATH: stride-docs

on:
  workflow_dispatch:
    inputs:
      skipPdfBuilding:
        description: Skip PDF building
        required: true
        default: 'Yes'
        type: choice
        options:
          - 'Yes'
          - 'No'
      skipApiBuilding:
        description: Skip API building
        required: true
        default: 'Yes'
        type: choice
        options:
          - 'Yes'
          - 'No'

jobs:
  publish-docs:
    runs-on: windows-latest

    steps:
    - name: Checkout Stride Docs
      uses: actions/checkout@v6
      with:
        path: ${{ env.DOCS_PATH }}
        lfs: true

    - name: Run Global Setup
      id: setup
      uses: ./.github/actions/setup-stride
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        skip-pdf-building: ${{ github.event.inputs.skipPdfBuilding }}
        skip-api-building: ${{ github.event.inputs.skipApiBuilding }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ env.DOCS_PATH }}/_site
        publish_branch: gh-pages