# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

# The Fast Track skips creating artifacts and compressing them
name: Build Stride Docs (Fast Track) for Azure Web App Staging

env:
  COMMON_SETTINGS_PATH: en/docfx.json
  VERSION: "2.0.0.${{ github.run_number }}"
  DOCS_PATH: stride-docs

on:
  workflow_dispatch:
    inputs:
      skipPdfBuilding:
        description: Skip PDF building
        required: true
        default: true
        type: boolean
      skipApiBuilding:
        description: Skip API building
        required: true
        default: true
        type: boolean
      strideBranch:
        description: Stride branch to checkout
        required: true
        default: master
        type: string

permissions:
  contents: read

jobs:
  build-deploy:
    # Run this job only if the repository is 'stride3d/stride-docs'
    if: github.repository == 'stride3d/stride-docs'
    runs-on: windows-2025-vs2026

    environment:
      name: 'Production'

    steps:
    # Checkout the Stride Docs repository from the branch that triggered the workflow
    - name: Checkout Stride Docs
      uses: actions/checkout@v6
      with:
        path: ${{ env.DOCS_PATH }}
        lfs: true

    - name: Run Global Setup
      id: setup
      uses: ./stride-docs/.github/actions/setup-stride
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        skip-pdf-building: ${{ inputs.skipPdfBuilding }}
        skip-api-building: ${{ inputs.skipApiBuilding }}
        stride-branch: ${{ inputs.strideBranch }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'stride-doc'
        slot-name: 'staging'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_32FCD402B970463A9143B24C9B225749 }}
        package: ./${{ env.DOCS_PATH }}/_site